sed -i 's/export function useAISettingsActions()/export type AIProvider = "openrouter" | "agnes" | "gemini";\n\nexport function useAISettingsActions()/' src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/provider: 'openrouter' | 'agnes'/provider: AIProvider/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/isTestingProvider: 'openrouter' | 'agnes' | null/isTestingProvider: AIProvider | null/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/isSavingKey: 'openrouter' | 'agnes' | null/isSavingKey: AIProvider | null/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/agnesApiKey ? '••••••••••••••••' : ''/agnesApiKey ? '••••••••••••••••' : ''\n  );\n  const [localGeminiKey, setLocalGeminiKey] = useState(\n    settings?.geminiApiKey ? '••••••••••••••••' : ''\n  );\n  const [geminiModel, setGeminiModel] = useState(String(settings?.geminiModel || 'gemini-2.0-flash'));\n  const [isEditingGemini, setIsEditingGemini] = useState(false);/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/useState<'openrouter' | 'agnes' | null>/useState<AIProvider | null>/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/agnes: !!settings?.agnesApiKey,/agnes: !!settings?.agnesApiKey,\n    gemini: !!settings?.geminiApiKey,/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/const field = provider === 'openrouter' ? 'openrouterApiKey' : 'agnesApiKey';/const field = provider === 'openrouter' ? 'openrouterApiKey' : provider === 'agnes' ? 'agnesApiKey' : 'geminiApiKey';/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/setLocalAgnesKey('••••••••••••••••');\n      }/setLocalAgnesKey('••••••••••••••••');\n      } else if (provider === 'gemini') {\n        setIsEditingGemini(false);\n        setLocalGeminiKey('••••••••••••••••');\n      }/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/const field = provider === 'openrouter' ? 'openrouterModel' : 'agnesModel';/const field = provider === 'openrouter' ? 'openrouterModel' : provider === 'agnes' ? 'agnesModel' : 'geminiModel';/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/const apiKey = provider === 'openrouter' ? settings?.openrouterApiKey : settings?.agnesApiKey;/const apiKey = provider === 'openrouter' ? settings?.openrouterApiKey : provider === 'agnes' ? settings?.agnesApiKey : settings?.geminiApiKey;/" src/features/settings/hooks/useAISettingsActions.ts
sed -i "s/setIsEditingAgnes,/setIsEditingAgnes,\n    localGeminiKey,\n    setLocalGeminiKey,\n    isEditingGemini,\n    setIsEditingGemini,\n    geminiModel,\n    setGeminiModel,/" src/features/settings/hooks/useAISettingsActions.ts
