export const QUERY_PARAMS = {
  SEARCH: 'q',
  CATEGORY: 'category',
  CATEGORIES: 'categories',
  TAGS: 'tags',
  SORT: 'sort',
  GROUP_ID: 'groupId',
  GROUPS: 'groups',
  BATCH: 'batch',
  SELECTED: 'selected',
  COLLAPSED: 'collapsed',
  ANCHOR: 'anchor',
  MODAL: 'modal',
  PHOTO_ID: 'photoId',
  COLS: 'cols',
  TAB: 'tab',
} as const;
