
export const PAGINATION = {
  LAZY_LOAD_COUNT: 20,
  INFINITE_MODE_COUNT: 10000,
  PUBLIC_PAGE_SIZE: 50,
};

export const IMAGE_COMPRESS = {
  MAX_WIDTH: 1200,
  QUALITY: 0.7,
};

export const AI_CONFIG = {
  CONCURRENCY: 3,
};
