import 'dotenv/config';
import postgres from 'postgres';

async function fixSystemLogs() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) return;
  
  const sql = postgres(connectionString);
  try {
    // Check if it's already an identity column
    await sql`
      ALTER TABLE "system_logs" 
      ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
    `;
    console.log('Successfully added identity to system_logs.id');
  } catch (err: any) {
    if (err.message.includes('already is an identity column')) {
      console.log('Already an identity column.');
    } else {
      console.error('Failed to fix system_logs:', err);
      // Try to create a sequence and set it as default
      try {
        await sql`CREATE SEQUENCE system_logs_id_seq;`;
        await sql`ALTER TABLE system_logs ALTER COLUMN id SET DEFAULT nextval('system_logs_id_seq');`;
        await sql`SELECT setval('system_logs_id_seq', COALESCE((SELECT MAX(id) FROM system_logs), 0) + 1);`;
        console.log('Successfully added sequence to system_logs.id');
      } catch (seqErr) {
        console.error('Failed to add sequence:', seqErr);
      }
    }
  } finally {
    await sql.end();
  }
}

fixSystemLogs();
