ALTER TABLE "system_logs" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "system_logs" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "system_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "system_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "system_logs" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "system_logs" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "system_logs" ADD COLUMN "error_message" text;--> statement-breakpoint
ALTER TABLE "system_logs" ADD COLUMN "stack_trace" text;--> statement-breakpoint
ALTER TABLE "system_logs" ADD COLUMN "component_stack" text;--> statement-breakpoint
ALTER TABLE "system_logs" ADD COLUMN "url" text;--> statement-breakpoint
ALTER TABLE "system_logs" ADD COLUMN "user_id" uuid;--> statement-breakpoint
ALTER TABLE "system_logs" ADD COLUMN "stack" text;--> statement-breakpoint
ALTER TABLE "system_logs" ADD COLUMN "context" text;--> statement-breakpoint
ALTER TABLE "settings" DROP COLUMN "categories_json";--> statement-breakpoint
ALTER TABLE "settings" DROP COLUMN "tags_json";--> statement-breakpoint
ALTER TABLE "settings" DROP COLUMN "manufacturers_json";--> statement-breakpoint
ALTER TABLE "settings" DROP COLUMN "primary_color";--> statement-breakpoint
ALTER TABLE "settings" DROP COLUMN "background_color";--> statement-breakpoint
ALTER TABLE "settings" DROP COLUMN "accent_color";--> statement-breakpoint
ALTER TABLE "settings" DROP COLUMN "contact_email";--> statement-breakpoint
ALTER TABLE "settings" DROP COLUMN "instagram";--> statement-breakpoint
ALTER TABLE "settings" DROP COLUMN "facebook";